### ISSUE TITLE
Datei-Download umständlich

### ISSUE THREAD

**Issue by s-at-dq** [Krassmus/Tresor#4]
Beim Klick auf eine Datei öffnet sich erst ein Dialog, in dem nur ein Download-Icon mit "Datei herunterladen" sichtbar ist. Allerdings öffnet sich direkt auch der Download-Dialog des Browsers (Firefox).

Es wäre besser, wenn direkt nach dem Klick auf die Datei der Download starten würde.

**Comment by Krassmus** [comment]
Der Dialog wird geladen, weil die Datei noch entschlüsselt werden muss. Mit etwas Umbau könnte das auch ohne Dialog gehen. Die Polizei interessiert sich aber nicht für dieses Feature, weil die eh nicht wollen, dass jemand die Dokumente herunterladen kann. Es geht also eher um das Betrachten.

**Comment by s-at-dq** [comment]
Ah ich sehe, dass PDF- und Bilddateien eingebettet angezeigt werden.
