### ISSUE TITLE
Datei-Download: Dateiname stimmt nicht

### ISSUE THREAD

**Issue by s-at-dq** [Krassmus/Tresor#5]
Wenn ich eine Datei herunterladen will, so wird deren richtiger Name, der z.B. im Dialogtitel angezeigt wird, nicht gesetzt. Ich erhalte stattdessen z.B. den Dateinamen "l59m1W4g". Wenn ich den Download-Dialog des Browsers mit Abbrechen schließe und im Tresor-Dialog auf "Datei herunterladen" klicke, lautet der Dateiname hingegen "undefined".

**Comment by Krassmus** [comment]
Auch das ist für die Polizei nicht wichtig, weil die gar nichts herunterladen.

**Comment by s-at-dq** [comment]
Das Problem taucht immer noch auf, wenn eine Datei nicht eingebettet angezeigt wird und vom Browser direkt der Download-Dialog angezeigt wird.

**Comment by Krassmus** [comment]
Wenn Du mir sagst, wie ich es besser mache, mache ich es gerne besser. Aber ich fürchte, bei data-urls geht es nicht besser:

https://stackoverflow.com/questions/283956/is-there-any-way-to-specify-a-suggested-filename-when-using-data-uri
