### ISSUE TITLE
"Datei aktualisieren für neue Schlüssel" funktioniert nicht

### ISSUE THREAD

**Issue by s-at-dq** [Krassmus/Tresor#6]
Die Sidebar-Aktion "Datei aktualisieren für neue Schlüssel" zeigt bei mir keine Wirkung. Die Dateien, die nochmal neu verschlüsselt werden müssen, sind nach dem Klick auf die Aktion immer noch nicht neu verschlüsselt worden.

**Comment by Krassmus** [comment]
Es kann sein, dass diese Aktion etwas dauert. Aber sie macht etwas. Im Anschluss sollte sich die Seite neu laden.

**Comment by s-at-dq** [comment]
Ich kann keine Aktivität feststellen: Es werden keine Requests gesendet und in der Konsole des Browsers werden auch keine Fehler angezeigt.

Es handelt sich um zwei Texte, die neu verschlüsselt werden sollen.

**Comment by Krassmus** [comment]
Besteht der Fehler noch? Die Seite wurde nicht neu geladen, wenn ein Text leer war.

**Comment by s-at-dq** [comment]
Jetzt habe ich das Problem, dass die Aktion überhaupt nicht mehr angezeigt wird. Das ist aber ein neues Problem, das ich in einem neuen Ticket beschreiben werde.

**Comment by Krassmus** [comment]
Vielleicht muss die Aktion ja gar nicht angezeigt werden?
