### ISSUE TITLE
Klick auf Text öffnet einen Dialog, der zum Bearbeiten einlädt

### ISSUE THREAD

**Issue by s-at-dq** [Krassmus/Tresor#7]
Wenn ich in der Liste mit Dateien und Texten auf den Namen eines Textes klicke, erscheint ein Dialog, in dem eine Textarea mit dem entschlüsselten Text angezeigt wird. Dies lädt zum Bearbeiten des Textes ein. Hier sollte der Text entweder nur angezeigt werden (z.B. innerhalb eines div) oder gleich der Bearbeiten-Dialog geladen werden.

**Comment by Krassmus** [comment]
Behoben. Das Textfeld ist jetzt readonly.
