### ISSUE TITLE
"Dateien aktualisieren für neue Schlüssel" wird nach Aus- und Eintragen nicht angezeigt

### ISSUE THREAD

**Issue by s-at-dq** [Krassmus/Tresor#8]
Ich habe in einer Veranstaltung das Problem, dass die Aktion "Dateien aktualisieren für neue Schlüssel" nicht mehr angezeigt wird, wenn jemand aus der Veranstaltung aus- und wieder eingetragen wird. Folgende Schritte habe ich mit test_dozent und test_autor durchgeführt:

- test_autor wird aus der Veranstaltung geworfen
- test_dozent legt einen neuen Text an
- test_autor wird in die Veranstaltung eingetragen: Der neue Text ist für ihn nicht lesbar.
- test_dozent ändert einen Text: Der neue Text ist für test_autor lesbar.

Allerdings fehlt die ganze Zeit die Aktion "Dateien aktualisieren für neue Schlüssel".

**Comment by Krassmus** [comment]
Das ist jetzt behoben.

Aber Moritz, Du sollst eigentlich sicherheitsrelevante Bugs finden und nicht Usability. Hast Du irgendwas zum Thema untersucht, ob man die Verschlüsselung brechen kann?
